# Locals
locals {
  credentials = [
    "arn:aws:dataprotection::aws:data-identifier/AwsSecretKey",
    "arn:aws:dataprotection::aws:data-identifier/OpenSshPrivateKey",
    "arn:aws:dataprotection::aws:data-identifier/PgpPrivateKey",
    "arn:aws:dataprotection::aws:data-identifier/PkcsPrivateKey",
    "arn:aws:dataprotection::aws:data-identifier/PuttyPrivateKey",
  ]

  device_identifiers = [
    "arn:aws:dataprotection::aws:data-identifier/IpAddress",
  ]

  financial_information = [
    "arn:aws:dataprotection::aws:data-identifier/BankAccountNumber-DE",
    "arn:aws:dataprotection::aws:data-identifier/BankAccountNumber-ES",
    "arn:aws:dataprotection::aws:data-identifier/BankAccountNumber-FR",
    "arn:aws:dataprotection::aws:data-identifier/BankAccountNumber-GB",
    "arn:aws:dataprotection::aws:data-identifier/BankAccountNumber-IT",
    "arn:aws:dataprotection::aws:data-identifier/BankAccountNumber-US",
    "arn:aws:dataprotection::aws:data-identifier/CreditCardExpiration",
    "arn:aws:dataprotection::aws:data-identifier/CreditCardNumber",
    "arn:aws:dataprotection::aws:data-identifier/CreditCardSecurityCode",
  ]

  phi = [
    "arn:aws:dataprotection::aws:data-identifier/DrugEnforcementAgencyNumber-US",
    "arn:aws:dataprotection::aws:data-identifier/HealthcareProcedureCode-US",
    "arn:aws:dataprotection::aws:data-identifier/HealthInsuranceCardNumber-EU",
    "arn:aws:dataprotection::aws:data-identifier/HealthInsuranceClaimNumber-US",
    "arn:aws:dataprotection::aws:data-identifier/HealthInsuranceNumber-FR",
    "arn:aws:dataprotection::aws:data-identifier/MedicareBeneficiaryNumber-US",
    "arn:aws:dataprotection::aws:data-identifier/NationalDrugCode-US",
    "arn:aws:dataprotection::aws:data-identifier/NationalInsuranceNumber-GB",
    "arn:aws:dataprotection::aws:data-identifier/NationalProviderId-US",
    "arn:aws:dataprotection::aws:data-identifier/NhsNumber-GB",
    "arn:aws:dataprotection::aws:data-identifier/PersonalHealthNumber-CA",
  ]

  pii = [
    "arn:aws:dataprotection::aws:data-identifier/Address",
    "arn:aws:dataprotection::aws:data-identifier/CepCode-BR",
    "arn:aws:dataprotection::aws:data-identifier/Cnpj-BR",
    "arn:aws:dataprotection::aws:data-identifier/CpfCode-BR",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-AT",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-AU",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-BE",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-BG",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-CA",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-CY",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-CZ",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-DE",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-DK",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-EE",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-ES",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-FI",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-FR",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-GB",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-GR",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-HR",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-HU",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-IE",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-IT",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-LT",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-LU",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-LV",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-MT",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-NL",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-PL",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-PT",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-RO",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-SE",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-SI",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-SK",
    "arn:aws:dataprotection::aws:data-identifier/DriversLicense-US",
    "arn:aws:dataprotection::aws:data-identifier/ElectoralRollNumber-GB",
    "arn:aws:dataprotection::aws:data-identifier/EmailAddress",
    "arn:aws:dataprotection::aws:data-identifier/IndividualTaxIdentificationNumber-US",
    "arn:aws:dataprotection::aws:data-identifier/InseeCode-FR",
    "arn:aws:dataprotection::aws:data-identifier/LatLong",
    "arn:aws:dataprotection::aws:data-identifier/Name",
    "arn:aws:dataprotection::aws:data-identifier/NationalIdentificationNumber-DE",
    "arn:aws:dataprotection::aws:data-identifier/NationalIdentificationNumber-ES",
    "arn:aws:dataprotection::aws:data-identifier/NationalIdentificationNumber-IT",
    "arn:aws:dataprotection::aws:data-identifier/NieNumber-ES",
    "arn:aws:dataprotection::aws:data-identifier/NifNumber-ES",
    "arn:aws:dataprotection::aws:data-identifier/PassportNumber-CA",
    "arn:aws:dataprotection::aws:data-identifier/PassportNumber-DE",
    "arn:aws:dataprotection::aws:data-identifier/PassportNumber-ES",
    "arn:aws:dataprotection::aws:data-identifier/PassportNumber-FR",
    "arn:aws:dataprotection::aws:data-identifier/PassportNumber-GB",
    "arn:aws:dataprotection::aws:data-identifier/PassportNumber-IT",
    "arn:aws:dataprotection::aws:data-identifier/PassportNumber-US",
    "arn:aws:dataprotection::aws:data-identifier/PermanentResidenceNumber-CA",
    "arn:aws:dataprotection::aws:data-identifier/PhoneNumber-BR",
    "arn:aws:dataprotection::aws:data-identifier/PhoneNumber-DE",
    "arn:aws:dataprotection::aws:data-identifier/PhoneNumber-ES",
    "arn:aws:dataprotection::aws:data-identifier/PhoneNumber-FR",
    "arn:aws:dataprotection::aws:data-identifier/PhoneNumber-GB",
    "arn:aws:dataprotection::aws:data-identifier/PhoneNumber-IT",
    "arn:aws:dataprotection::aws:data-identifier/PhoneNumber-US",
    "arn:aws:dataprotection::aws:data-identifier/PostalCode-CA",
    "arn:aws:dataprotection::aws:data-identifier/RgNumber-BR",
    "arn:aws:dataprotection::aws:data-identifier/SocialInsuranceNumber-CA",
    "arn:aws:dataprotection::aws:data-identifier/Ssn-ES",
    "arn:aws:dataprotection::aws:data-identifier/Ssn-US",
    "arn:aws:dataprotection::aws:data-identifier/TaxId-DE",
    "arn:aws:dataprotection::aws:data-identifier/TaxId-ES",
    "arn:aws:dataprotection::aws:data-identifier/TaxId-FR",
    "arn:aws:dataprotection::aws:data-identifier/TaxId-GB",
    "arn:aws:dataprotection::aws:data-identifier/VehicleIdentificationNumber",
    "arn:aws:dataprotection::aws:data-identifier/ZipCode-US",
  ]

  protection_list = concat(
    var.protection_policy.credentials ? local.credentials : [],
    var.protection_policy.device_identifiers ? local.device_identifiers : [],
    var.protection_policy.financial_information ? local.financial_information : [],
    var.protection_policy.phi ? local.phi : [],
    var.protection_policy.pii ? local.pii : []
  )
}
